# Generated by Django 5.2.4 on 2025-07-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Что именно вы будете делать? (например, 'пить стакан воды')",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Когда выполнять привычку? (например, '18:00')",
                        verbose_name="Время",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где выполнять привычку? (например, 'на кухне')",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Будет ли эта привычка видна другим пользователям?",
                        verbose_name="Публичная привычка",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Является ли эта привычка приятной (используется как вознаграждение)?",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки (не более 2 минут).",
                        null=True,
                        verbose_name="Время на выполнение (мин.)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем вознаградить себя после выполнения полезной привычки? (например, 'купить десерт')",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "periodicity_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Как часто повторять привычку в днях. Например, 1 (ежедневно), 7 (еженедельно).",
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, которая выполняется в качестве вознаграждения.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="useful_habits_rewarded_by_me",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Создатель привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "unique_together": {("user", "action", "time", "place")},
            },
        ),
    ]
