# Generated by Django 5.2.4 on 2025-07-24 19:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_completed",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Дата, когда привычка была выполнена",
                        verbose_name="Дата выполнения",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "habit",
                    models.ForeignKey(
                        help_text="Выполненная привычка",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="habits.habit",
                        verbose_name="Привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, выполнивший привычку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-date_completed"],
                "unique_together": {("user", "habit", "date_completed")},
            },
        ),
    ]
