# Generated by Django 5.2.4 on 2025-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habitcompletion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="duration_minutes",
        ),
        migrations.AddField(
            model_name="habit",
            name="duration",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд).",
                null=True,
                verbose_name="Время на выполнение (сек.)",
            ),
        ),
    ]
