# Generated by Django 5.2.4 on 2025-07-26 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_duration_minutes_habit_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="habit",
            unique_together={("owner", "action", "time", "place")},
        ),
    ]
