# Generated by Django 5.2.4 on 2025-07-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_rename_user_habit_owner_alter_habit_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HabitCompletion",
        ),
    ]
